FROM alpine:3.16

RUN apk update && \
  apk add --no-cache curl ca-certificates && \
  rm -rf /var/cache/apk/*

WORKDIR /app

ADD go-ldap-ovpn /app/go-ldap-ovpn
RUN chmod u+x /app/go-ldap-ovpn

# Start
ENTRYPOINT [ "/app/go-ldap-ovpn" ]